### ISSUE TITLE
[Insight] Your project should not contain &quot;FIXME&quot; comments - in .github/workflows/main.yml, line 109

### ISSUE THREAD

**Issue by tarlepp** [tarlepp/symfony-flex-backend#1144]
**[in .github/workflows/main.yml, line 109](https://github.com/tarlepp/symfony-flex-backend/blob/b4bb636147b9ae007de4422d5f081e6f3b3130d7/.github/workflows/main.yml#L109)**

> Tasks comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```
        uses: actions/upload-artifact@v1
        with:
          name: psalm.json
          path: ./build/psalm.json

      # TODO: enable this when https://github.com/nunomaduro/phpinsights has new version
      #- name: Archive `phploc` results (phploc.json)
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: phploc.json
      #    path: ./build/phploc.json
```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/e59c1ed3-b870-457a-971e-570a27a04784/analyses/3599)_
